use_frameworks!

platform :ios, '8.3'

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'PsiphonClientCommonLibrary_Example' do
  pod 'InAppSettingsKit', :git => 'https://github.com/Psiphon-Inc/InAppSettingsKit.git', :commit => '8bd203c'
  #pod 'InAppSettingsKit', :path => '../../InAppSettingsKit'

  pod 'PsiphonClientCommonLibrary', :path => '../'

  target 'PsiphonClientCommonLibrary_Tests' do
    inherit! :search_paths


  end
end
