use_frameworks!

target 'PsiphonClientCommonLibrary_Example' do
  pod 'PsiphonClientCommonLibrary', :path => '../'

  target 'PsiphonClientCommonLibrary_Tests' do
    inherit! :search_paths

    
  end
end
